import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SessionProviderComponent from "@/components/SessionProvider";
import Footer from "@/components/Footer";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: { default: "Next-Auth.js", template: "%s | Next-Auth.js" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-gray-200`}>
        <SessionProviderComponent>
          <Header />
          {children}
        </SessionProviderComponent>
      </body>
    </html>
  );
}
